# 服务器
server:
  port: 8080

# spring
spring:
  # 数据连接池
  datasource:
    username: cwk
    password: chenwenkang
    url: jdbc:mysql://120.24.55.61:3306/weshare?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  ## Redis 配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 8
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 1200

  # 上传服务
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  #jpa
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto : validate                 # Hibernate ddl auto (create, create-drop, validate, update)
    show-sql: true

  # 邮箱
  mail:
    host: smtp
    username: HNUWeShare@163.com
    password: MMGZIVTOXBKSQJVW
    port: 465
    properties.smtp.auth: true
    properties.smtp.timeout: 2500
    properties.mail.smtp.ssl.enable: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# 日志信息
logging:
  level:
    com:
      springsecurity:
        demo: DEBUG
    org:
      hibernate: WARN
      springframework: WARN

# 上传路径
upload:
  dir : /home/WeShare/assets/

# 图片网络访问路径
img:
  imgURL: http://120.24.55.61:8080/images/